version: '3'
services:
    postgresql:
        image: postgres:10.12
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=my_db
        volumes:
            - db-data:/var/lib/postgresql/data/
        ports:
            - 5432:5432
    
volumes:
    db-data:
